modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="RiffedCheats"
description='''Client-side cheat / trainer menu inspired by CheatUtils, styled like YimMenuV2. Works in your own worlds, and on servers only with operator rights.'''

[[mixins]]
config="riffedcheats.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="CLIENT"
